### PR TITLE
Added multi track support

### PR DESCRIPTION
**Pull request by makinori**
I rewrote part of the code to transform the midi file into a map with:
`note time -> array of pitch and instrument`

Then sort the map entries and !combine the note array together and add !stop accordingly.

It seems to work pretty well! Thanks for making this lol, it was fun to play with. I hope I didn't remove too much of your original code.

https://user-images.githubusercontent.com/8362329/153554148-7bd8e68b-e98b-4309-9f6e-488366fbf91d.mp4

### CODE REVIEW

**Comment by makinori** [comment]
Aw it seems like its not combining the notes well enough or maybe it's just this midi. I'm a little confused with the bmp value, im just multiplying it by anything from 0.2 to 0.6

https://user-images.githubusercontent.com/8362329/153556094-71ffe035-01e0-48de-8695-1194166af5de.mp4

**Comment by makinori** [comment]
https://user-images.githubusercontent.com/8362329/153559356-ad2cbbc2-74db-4a8f-ac00-2831ee8361a5.mp4

**Comment by makinori** [comment]
https://user-images.githubusercontent.com/8362329/153560656-ecfde06f-ebb1-4e4b-bb93-b92ec915ca0d.mp4

**Comment by makinori** [comment]
Aah I realized I should be playing with `waitMultiplier` not bpm

**Review by suchipi — APPROVED** [review]
Thanks!! :D

**Pull request merged**
